version: '2'
services:
  node1:
    container_name: node1
    environment:
      - PEERS=http://node2:3002;http://node3:3003
      - HTTP_PORT=3001
    build:
      context: ./
      dockerfile: Dockerfile.dec
    ports:
        - "3001:3001"
    networks:
      default:
        aliases:
          - node1
  node2:
    container_name: node2
    environment:
      - PEERS=http://node1:3001;http://node3:3003
      - HTTP_PORT=3002
    build:
      context: ./
      dockerfile: Dockerfile.dec
    ports:
    - "3002:3002"
    networks:
      default:
        aliases:
          - node2
  node3:
    container_name: node3
    environment:
      - PEERS=http://node1:3001;http://node2:3002
      - HTTP_PORT=3003
    build:
      context: ./
      dockerfile: Dockerfile.dec
    ports:
        - "3003:3003"
    networks:
      default:
        aliases:
          - node3
  wallet:
    container_name: wallet
    environment:
      - PORTS=3001;3002;3003
      - HTTP_PORT=4200
      - HOST=$DOCKER_HOST
    build:
      context: ./blockchain-nodejs-wallet/
      dockerfile: Dockerfile
    ports:
        - "4200:4200"
networks:
    default:
